#!/usr/bin/env python3
"""
TROS PRO — Multi-platform KOL Scraper (TikTok + Facebook) via yt-dlp.
Scrapes views/likes/shares/comments/saves/followers from each post link.
Usage: python3 scripts/scraper.py [output_json]
"""
import json, sys, subprocess, time, random

# KOLs that yt-dlp cannot fetch (age-restricted / login / Facebook private).
# Paste the latest numbers you read by eye; they override the auto-scrape.
MANUAL_OVERRIDE = {
    # 'handle': {'views':0,'likes':0,'shares':0,'comments':0,'saves':0,'followers':0},
}

# handle -> {url, platform}  (generated by kol-dashboard-generator)
KOL_LINKS = {
    "bass__inmeesub": {
        "url": "https://vt.tiktok.com/ZSXgmUfA8/",
        "platform": "TikTok"
    },
    "kuanpuantiew": {
        "url": "https://vt.tiktok.com/ZSXgqSFbs/",
        "platform": "TikTok"
    },
    "juno55555": {
        "url": "https://vt.tiktok.com/ZSXgpUoF4/",
        "platform": "TikTok"
    },
    "pluemwattanathon": {
        "url": "https://vt.tiktok.com/ZSXgCbosJ/",
        "platform": "TikTok"
    },
    "bee112711": {
        "url": "https://vt.tiktok.com/ZSXgmXbkW/",
        "platform": "TikTok"
    },
    "kunofficial29": {
        "url": "https://vt.tiktok.com/ZSXqv1ytm/",
        "platform": "TikTok"
    },
    "pakkaput17": {
        "url": "https://vt.tiktok.com/ZSXb9cbeX/",
        "platform": "TikTok"
    },
    "benmar_98": {
        "url": "https://vt.tiktok.com/ZSXg96w3m/",
        "platform": "TikTok"
    },
    "sapol_mu_": {
        "url": "https://vt.tiktok.com/ZSXguN6Gr/",
        "platform": "TikTok"
    },
    "folk.rt": {
        "url": "https://vt.tiktok.com/ZSXggLvfp/",
        "platform": "TikTok"
    },
    "homchuy": {
        "url": "https://vt.tiktok.com/ZSXgp9fcv/",
        "platform": "TikTok"
    },
    "pangpon.thatpong": {
        "url": "https://vt.tiktok.com/ZSXgwqy9u/",
        "platform": "TikTok"
    },
    "pattarapon_mike": {
        "url": "https://vt.tiktok.com/ZSXgQGLjv/",
        "platform": "TikTok"
    },
    "mac5869": {
        "url": "https://vt.tiktok.com/ZSXgqvweV/",
        "platform": "TikTok"
    },
    "ig_earthalert24": {
        "url": "https://vt.tiktok.com/ZSXgm3eLV/",
        "platform": "TikTok"
    },
    "i.thinnajohn": {
        "url": "https://vt.tiktok.com/ZSXbPDroy/",
        "platform": "TikTok"
    },
    "artchanathip.ppppp": {
        "url": "https://vt.tiktok.com/ZSXgxGT7k/",
        "platform": "TikTok"
    }
}


def yt(url, extra=None, timeout=60):
    cmd = ['yt-dlp','--dump-json','--no-download','--no-warnings']
    if extra: cmd += extra
    cmd += [url]
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)


def scrape(url, platform):
    try:
        r = yt(url)
        if r.returncode != 0:
            # retry age-gate for TikTok
            r = yt(url, ['--age-limit','99'])
            if r.returncode != 0:
                print(f"    yt-dlp error: {r.stderr.strip()[:160]}")
                return None
        info = json.loads(r.stdout)
        return {
            'url': info.get('webpage_url', url),
            'platform': platform,
            'views': info.get('view_count', 0) or 0,
            'likes': info.get('like_count', 0) or 0,
            'shares': info.get('repost_count', 0) or 0,
            'comments': info.get('comment_count', 0) or 0,
            'saves': (info.get('save_count') or info.get('collect_count')
                      or info.get('favorite_count') or info.get('bookmark_count') or 0),
            'followers': info.get('channel_follower_count', 0) or 0,
        }
    except subprocess.TimeoutExpired:
        print(f"    Timeout: {url}"); return None
    except json.JSONDecodeError:
        print(f"    JSON parse error: {url}"); return None
    except Exception as e:
        print(f"    Error: {e}"); return None


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'scrape_results.json'
    active = {k:v for k,v in KOL_LINKS.items() if v.get('url','').strip()}
    results = {}
    print(f"Scraping {len(active)} post(s)...")
    for handle, info in active.items():
        if handle in MANUAL_OVERRIDE:
            results[handle] = {**MANUAL_OVERRIDE[handle], 'url': info['url'], 'platform': info['platform']}
            print(f"  @{handle} — manual override"); continue
        print(f"  @{handle} [{info['platform']}] ...")
        data = scrape(info['url'], info['platform'])
        if data:
            results[handle] = data
            print(f"    views {data['views']:,} | likes {data['likes']:,} | "
                  f"cmt {data['comments']:,} | shr {data['shares']:,} | save {data['saves']:,}")
        else:
            print(f"    FAILED @{handle}")
        time.sleep(random.uniform(0.5, 1.5))
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\nSaved {len(results)}/{len(active)} -> {out}")


if __name__ == '__main__':
    main()
